package StockmarketApp;


/**
* StockmarketApp/StockmarketOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Stockmarket.idl
* Tuesday, August 9, 2022 6:00:15 PM BST
*/

public interface StockmarketOperations 
{
  double retrieveSME (String name);
  void shutdown ();
} // interface StockmarketOperations
