package StockmarketApp;


/**
* StockmarketApp/StockmarketHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Stockmarket.idl
* Tuesday, August 9, 2022 6:00:15 PM BST
*/

abstract public class StockmarketHelper
{
  private static String  _id = "IDL:StockmarketApp/Stockmarket:1.0";

  public static void insert (org.omg.CORBA.Any a, StockmarketApp.Stockmarket that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static StockmarketApp.Stockmarket extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (StockmarketApp.StockmarketHelper.id (), "Stockmarket");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static StockmarketApp.Stockmarket read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_StockmarketStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, StockmarketApp.Stockmarket value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static StockmarketApp.Stockmarket narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof StockmarketApp.Stockmarket)
      return (StockmarketApp.Stockmarket)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      StockmarketApp._StockmarketStub stub = new StockmarketApp._StockmarketStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static StockmarketApp.Stockmarket unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof StockmarketApp.Stockmarket)
      return (StockmarketApp.Stockmarket)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      StockmarketApp._StockmarketStub stub = new StockmarketApp._StockmarketStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
