package StockmarketApp;

import java.util.HashMap;
import org.omg.PortableServer.Servant;


/**
* StockmarketApp/StockmarketPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Stockmarket.idl
* Tuesday, August 9, 2022 6:00:15 PM BST
*/

public abstract class StockmarketPOA extends Servant
 implements StockmarketApp.StockmarketOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
@SuppressWarnings("unchecked")
 // private static final HashMap _methods = new HashMap ();
  private static HashMap<String, Integer> _methods  = new HashMap<String, Integer>();
  static
  {
    _methods.put("retrieveSME", 0);
    _methods.put("shutdown", 1);
  }

  @Override
  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method)
    {
       case 0:  // StockmarketApp/Stockmarket/retrieveSME
       {
         String name = in.read_string ();
         double $result;
         $result = this.retrieveSME (name);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 1:  // StockmarketApp/Stockmarket/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static final String[] __ids = {
    "IDL:StockmarketApp/Stockmarket:1.0"};

  @Override
  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Stockmarket _this() 
  {
    return StockmarketHelper.narrow(
    super._this_object());
  }

  public Stockmarket _this(org.omg.CORBA.ORB orb) 
  {
    return StockmarketHelper.narrow(
    super._this_object(orb));
  }


} // class StockmarketPOA
