package StockmarketApp;

/**
* StockmarketApp/StockmarketHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Stockmarket.idl
* Tuesday, August 9, 2022 6:00:15 PM BST
*/

public final class StockmarketHolder implements org.omg.CORBA.portable.Streamable
{
  public StockmarketApp.Stockmarket value = null;

  public StockmarketHolder ()
  {
  }

  public StockmarketHolder (StockmarketApp.Stockmarket initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StockmarketApp.StockmarketHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StockmarketApp.StockmarketHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StockmarketApp.StockmarketHelper.type ();
  }

}
